version: "3.9"

services:
  # server:
  #   build: ./server
  #   container_name: express-server
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - fullstack-net
  #   restart: unless-stopped
  client:
    build: ./
    container_name: build-billing-app
    ports:
      - "5174:3000"
    networks:
      - fullstack-net
    # depends_on:
    #   - server
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge
